workflows:
  ios-workflow:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Create iOS platform folder
        script: | 
          flutter create --org com.example --platforms=ios .
      - name: Get Flutter dependencies
        script: | 
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: | 
          cd ios
          pod install
      - name: Build iOS without code signing
        script: | 
          flutter build ios --release --no-codesign
      - name: Create IPA manually
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r app.ipa Payload
    artifacts:
      - app.ipa
      - build/ios/iphoneos/Runner.app
