workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      groups:
        - production_secrets  # Your env variables
      flutter: stable
      xcode: latest
    scripts:
      - name: Generate iOS folder
        script: |
          flutter create --platforms ios .
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
